### PR TITLE
Update pytest to 3.0.1

### PR DESCRIPTION
**Pull request by stephendonner**
@mozilla/web-qa-apprentices / @mozilla/web-qa-sorcerers r?

### CODE REVIEW

**Comment by stephendonner** [comment]
@davehunt / @Standard8 r?

**Comment by stephendonner** [comment]
Unsupported-browser ad-hoc: https://pastebin.mozilla.org/8906230
Supported-browser ad-hoc: https://pastebin.mozilla.org/8906231

**Comment by rbillings** [comment]
R+

**Comment by stephendonner** [comment]
Thx; merging in.

**Pull request merged**
