### PR TITLE
Update pytest and un-pin pytest-selenium

### PR DESCRIPTION
**Pull request by stephendonner**

### CODE REVIEW

**Comment by davehunt** [comment]
Could you add pytest-xdist to requirements.txt to avoid issues with incompatible versions in CI?

**Comment by stephendonner** [comment]
Hold off on this for now; it's failing in the ad-hoc run, and I'm trying to get it to run locally using Sauce Labs :-(

**Comment by davehunt** [comment]
I fixed the adhoc job configuration - it was a missing environment variable. Here's a [passing adhoc job](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/hello.adhoc/39).

**Comment by davehunt** [comment]
aaaand r+ :deciduous_tree:

**Comment by stephendonner** [comment]
Thanks, Dave!

**Pull request merged**
